import { user } from "./auth-schema";
import { jsonb, pgTable, primaryKey, text, timestamp } from "drizzle-orm/pg-core";
import type { LabSnapshot } from "~~/services/store/lab-persistence";

// auth-schema.ts is generated by `yarn auth:generate` from lib/auth.ts — never edit it by hand.
// Our own tables live here. Column names come from drizzle's `casing: "snake_case"` (drizzle.config.ts
// + postgresClient.ts); the generated file spells its names out, which drizzle honours as-is.
export * from "./auth-schema";

export const labProgress = pgTable(
  "lab_progress",
  {
    userId: text()
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    labId: text().notNull(),
    snapshot: jsonb().$type<LabSnapshot>().notNull(),
    startedAt: timestamp({ withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp({ withTimezone: true }).notNull().defaultNow(),
  },
  t => [primaryKey({ columns: [t.userId, t.labId] })],
);
