// AUTO-GENERATED by scripts/gen-lab-sources.ts from contracts/*.sol — do not
// edit by hand; edit the .sol files and re-run the script.

export const contracts: Record<string, string> = {
  "Adder.sol":
    'pragma solidity ^0.8.20;\n\ncontract Adder {\n  // <region id="add-fn" scope="member">\n  function add(uint256 a, uint256 b) public pure returns (uint256) {\n    return a + b;\n  }\n  // </region>\n}\n',
};
