// Regenerates labs/<id>/contracts.gen.ts from labs/<id>/contracts/*.sol.
//
// The .sol files are the source of truth (real solidity, open in any editor,
// diff like code). This snapshot exists only because the bundler can't import
// .sol as text without loader config that differs between webpack and
// turbopack. validate-labs fails if a snapshot is stale.
//
// Run from packages/nextjs:  yarn gen:labs
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const labsRoot = path.resolve(here, "../labs");

for (const labId of fs.readdirSync(labsRoot)) {
  const contractsDir = path.join(labsRoot, labId, "contracts");
  if (!fs.existsSync(contractsDir) || !fs.statSync(contractsDir).isDirectory()) continue;

  const files = fs
    .readdirSync(contractsDir)
    .filter(f => f.endsWith(".sol"))
    .sort();
  if (!files.length) continue;

  let body = "";
  for (const f of files) {
    const source = fs.readFileSync(path.join(contractsDir, f), "utf8");
    body += `  ${JSON.stringify(f)}: ${JSON.stringify(source)},\n`;
  }

  const out = `// AUTO-GENERATED by scripts/gen-lab-sources.ts from contracts/*.sol — do not
// edit by hand; edit the .sol files and re-run the script.

export const contracts: Record<string, string> = {
${body}};
`;
  fs.writeFileSync(path.join(labsRoot, labId, "contracts.gen.ts"), out);
  console.log(`labs/${labId}: snapshotted ${files.join(", ")}`);
}
