// Regenerates lib/solc/oz-sources.ts — a vendored map of the OpenZeppelin
// Solidity sources the in-browser compiler needs, keyed by the exact path solc
// requests.
//
// Why: the solc web-worker compiles in the browser with no filesystem, so a
// lab contract's real `import "@openzeppelin/contracts/..."` lines can't hit
// node_modules. We crawl the import graph from the entry points below, snapshot
// every file as a string, and resolve imports against that map before compiling.
//
// Run:  yarn gen:oz
import { collectImportGraph } from "../lib/solc/resolve-imports";
import fs from "node:fs";
import { createRequire } from "node:module";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const nextjsRoot = path.resolve(here, "..");

// @openzeppelin/contracts is a build-time-only devDependency of this workspace
// (the browser compiles against the vendored map this script emits, never
// node_modules). Resolve it through node module resolution rather than guessing
// paths, so vendoring doesn't depend on hoisting or on the hardhat workspace —
// the learning lab is a frontend project and hardhat will eventually be dropped.
const require = createRequire(import.meta.url);
const ozRoot = path.resolve(path.dirname(require.resolve("@openzeppelin/contracts/package.json")), "../..");

const OUT = path.join(nextjsRoot, "lib/solc/oz-sources.ts");

// Everything the current labs import. Add entry points here when a future lab
// needs more of OZ, then re-run this script.
const entryPoints = ["@openzeppelin/contracts/token/ERC20/ERC20.sol", "@openzeppelin/contracts/access/Ownable.sol"];

// @-scoped keys map straight onto OZ's on-disk layout under ozRoot. Return
// undefined on a miss so the crawler reports the unresolved import by name.
const collected = collectImportGraph(entryPoints, key => {
  const file = path.join(ozRoot, key);
  return fs.existsSync(file) ? fs.readFileSync(file, "utf8") : undefined;
});

const ozVersion = (
  JSON.parse(fs.readFileSync(path.join(ozRoot, "@openzeppelin/contracts/package.json"), "utf8")) as { version: string }
).version;

const header = `// AUTO-GENERATED by scripts/gen-oz-sources.ts — do not edit by hand.
// Vendored OpenZeppelin v${ozVersion} sources keyed by the exact import path solc
// requests, so a lab's real \`import "@openzeppelin/contracts/..."\` lines
// resolve in-browser with no network and no flattening.

export const OZ_SOURCES: Record<string, string> = {
`;

// Sorted so the generated file is stable regardless of crawl / entry-point order.
const keys = Object.keys(collected).sort();
let body = "";
for (const k of keys) body += `  ${JSON.stringify(k)}: ${JSON.stringify(collected[k])},\n`;
fs.writeFileSync(OUT, header + body + "};\n");

console.log(`Wrote ${keys.length} OZ v${ozVersion} files to lib/solc/oz-sources.ts`);
