// AUTO-GENERATED by scripts/gen-lab-sources.ts from contracts/*.sol — do not
// edit by hand; edit the .sol files and re-run the script.

export const contracts: Record<string, string> = {
  "Counter.sol":
    'pragma solidity ^0.8.20;\n\ncontract Counter {\n  // <region id="storage" scope="member">\n  uint256 public number = 42;\n  // </region>\n\n  // <region id="event" scope="member">\n  event NumberChanged(uint256 newNumber);\n  // </region>\n\n  // <region id="increment" scope="member">\n  function increment() public {\n    number += 1;\n  }\n  // </region>\n\n  // <region id="setter" scope="member">\n  function setNumber(uint256 newNumber) public {\n    number = newNumber;\n    emit NumberChanged(newNumber);\n  }\n  // </region>\n}\n',
};
